tasks:
  - init: git remote set-url origin git@github.com:pavithra-nagarajan/pavithra-nagarajan-BooleanOperators.git && sed "s/\r$//" commit-command.sh | bash && gp open README.md
  - command: sleep 5 && code --install-extension redhat.java && sleep 5 && code --install-extension vscjava.vscode-java-debug && sleep 40 && code --install-extension kyntrack.gitpod-tracker-plugin
