tasks:
  - init: git remote set-url origin git@github.com:pavithra-nagarajan/pavithra-nagarajan-BooleanOperators.git && sed "s/\r$//" commit-command.sh | bash && gp open README.md
  - command: code --install-extension vscjava.vscode-java-debug && code --install-extension redhat.java 
